# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='角色权限'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户角色'),
        ),
    ]
