# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180126_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_group',
            field=models.BooleanField(verbose_name='是否是组'),
        ),
    ]
